# Generated by Django 3.1.3 on 2020-11-20 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rfid', models.CharField(max_length=200)),
                ('face_embedding', models.CharField(max_length=200)),
                ('vein_embedding', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AccessHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('face_check', models.CharField(max_length=100)),
                ('temp', models.FloatField()),
                ('vein_check', models.CharField(max_length=100)),
                ('rfid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.embedding')),
            ],
        ),
    ]
